### ISSUE TITLE
Amazon SQS input/output

### ISSUE THREAD

**Issue by bcjwilson** [brightcove/watchmen#12]
It would be nice if watchmen could push messages to an [Amazon SQS](http://aws.amazon.com/sqs/) queue and read messages from a queue.

**Comment by gkatsev** [comment]
yes it would. PRs welcome. :tongue:

**Comment by bcjwilson** [comment]
Haha, thanks. I might do this.

Some queuing systems have a delete concept to signal that the work/message was successfully processed. We currently don't have something like this in watchmen that I know of. I'm not sure how we'd represent that, do you?

**Comment by gkatsev** [comment]
Nope. One way of doing it is to just bind the other direction via watchmen and have the end point handle sending the delete itself.
